---
build_from:
  aarch64: dockerproxy.net/home-assistant/aarch64-base:3.19
  amd64: dockerproxy.net/home-assistant/amd64-base:3.19
  armhf: dockerproxy.net/home-assistant/armhf-base:3.19
  armv7: dockerproxy.net/home-assistant/armv7-base:3.19
  i386: dockerproxy.net/home-assistant/i386-base:3.19
